
spring:
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/schoolmaster_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
